### ISSUE TITLE
ee.ee_exception.EEException: Number of bands (1236) must be less than or equal to 1024.

### ISSUE THREAD

**Issue by kpoman** [dugalh/geedim#10]
Hello,
I am downloading an imagecollection as a single image using toBands() method. It exceeds the max number of bands. I was wodnering if this lib, given it already takes care of image size, could also take care of number of bands to decide for a split.
Thank you

**Comment by dugalh** [comment]
Hi.  This would be quite a big change for what seems to be an uncommon use.  You could iterate over the collection and download each image separately...
