### ISSUE TITLE
Export to google cloud storage bucket fails w/ `ee.ee_exception.EEException: Unknown configuration options: {'assetId': 'test'}`.

### ISSUE THREAD

**Issue by brownag** [dugalh/geedim#14]
Thank you for this excellent tool! I was playing around with the new export function/types and ran into a minor issue with export to google cloud bucket. When using `export()` with `ExportType` `"cloud"` and `filename` e.g. `"test"` I get:
```
ee.ee_exception.EEException: Unknown configuration options: {'assetId': 'test'}
```

It appears that `assetId` is not an argument of [`Export.image.toCloudStorage()`](https://developers.google.com/earth-engine/apidocs/export-image-tocloudstorage). I think it should work to set just `description` here:

https://github.com/dugalh/geedim/blob/7d8ecfcb2e4505192a3e19364fc0afcfda7452ae/geedim/download.py#L805-L808

**Comment by dugalh** [comment]
Hi Andrew.  Thanks for picking this up.  It should be fixed now with [v1.6.1](https://github.com/dugalh/geedim/releases/tag/v1.6.1).  Can you confirm it is working for you?

**Comment by brownag** [comment]
@dugalh Thanks Dugal! I confirm it is working w/ [v1.6.1](https://github.com/dugalh/geedim/releases/tag/v1.6.1)

**Comment by dugalh** [comment]
Great - thank you!
