### ISSUE TITLE
Yearly composite problem

### ISSUE THREAD

**Issue by sticks0220** [dugalh/geedim#16]
Hello. I have a problem with uploading an annual composite to a certain territory. When part of the image is loaded, it gives me an error:

Error downloading tile: Expected a homogeneous image collection, but an image with incompatible bands was encountered: First image type: 23 bands ([B1, B2, B3, B4, B5, B6, B7, B8, B8A, B9, B11, B12, AOT, WVP, SCL, TCI_R, TCI_G, TCI_B, MSK_CLDPRB, MSK_SNWPRB, QA10, QA20, QA60]). Current image type: 21 bands ([B1, B2, B3, B4, B5, B6, B7, B8, B8A, B9, B11, B12, AOT, WVP, SCL, TCI_R, TCI_G, TCI_B, QA10, QA20, QA60]).

Is there a way around this error?

**Comment by dugalh** [comment]
Hello.  It looks like some images in your collection don't have the MSK_CLDPRB and MSK_SNWPRB bands.  On the [Sentinel-2 help page](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED) it says these bands are  "missing in some products".   I suggest using [ee.ImageCollection.select](https://developers.google.com/earth-engine/apidocs/ee-imagecollection-select) to select the 21 bands of the "current image type" on the Sentinel-2 collection, before wrapping it in [geedim.MaskedImageCollection](https://geedim.readthedocs.io/en/latest/api.html#geedim.collection.MaskedCollection).  Then form the composite and download.
